### ISSUE TITLE
No Unit Tests

### ISSUE THREAD

**Issue by seriouscoderone** [nickelser/pg_kinesis#5]
Please add unit tests. Some refactoring is needed to make it unit-testable.

**Comment by diranged** [comment]
@josephleehunsaker I am beginning work on refactoring this code as well. I've started some initial work on a test-runner here (https://github.com/diranged/pg_kinesis/pull/1). Its obviously not doing anything really useful yet, but you can see where I'm going. I hope to have some real tests running against it by tonight.

The approach I am taking is to _start_ with integration tests. Once I have those working, I'll start refactoring bits and adding unit tests as I go.

**Comment by diranged** [comment]
@nickelser, my PR (https://github.com/diranged/pg_kinesis/pull/1) is still under a bit of development, but I'd love to know if you will consider accepting it. I haven't seen any responses from you on the issues in this repo, so its unclear whether or not you are actively developing this project.

**Comment by nickelser** [comment]
hey, i'm looking at my projects now. i haven't been a great maintainer, but trying to catch up :-) better late than never!

your PR looks great and i'd love to merge it!
